### ISSUE TITLE
Bug in position_switch_disconnectors

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#136]
Running edisgo for the cluster grids three of these grids (1977, 2490, 3021) threw the following error.
@gplssm could you have a look at it?

```
INFO:root:Running grid 1977
Traceback (most recent call last):
  File "/home/Birgit.Schachler/virtualenvs/open_ego_storage_positioning/git_repos/eDisGo/edisgo/examples/test_revision_reinforcement.py", line 14, in <module>
    worst_case_analysis='worst-case-feedin')
  File "/home/Birgit.Schachler/virtualenvs/open_ego_storage_positioning/git_repos/eDisGo/edisgo/grid/network.py", line 193, in __init__
    self.import_from_ding0(kwargs.get('ding0_grid', None))
  File "/home/Birgit.Schachler/virtualenvs/open_ego_storage_positioning/git_repos/eDisGo/edisgo/grid/network.py", line 238, in import_from_ding0
    network=self.network)
  File "/home/Birgit.Schachler/virtualenvs/open_ego_storage_positioning/git_repos/eDisGo/edisgo/data/import_data.py", line 97, in import_from_ding0
    'position'])
  File "/home/Birgit.Schachler/virtualenvs/open_ego_storage_positioning/git_repos/eDisGo/edisgo/grid/tools.py", line 183, in position_switch_disconnectors
    node1 = ring[position - 1]
IndexError: list index out of range
```

**Comment by gplssm** [comment]
I tracked it down to the root. Now, instead of calling it a bug of eDisGo, I would call it an unintended feature of Ding0.

**Decision**

- We break our strict rule of positioning switch disconnecters only at LV stations -> if no station available, it uses other nodes as well
- User will be notified in debug mode

**Comment by gplssm** [comment]
The successful implementation was tested with grids 2490, 3021, and 1977.

Note, grid 3021 did not converge in the PFA. This is discussed in #69
