### ISSUE TITLE
[BUG] Tests failing for 3.7

### ISSUE THREAD

**Issue by mltja** [openego/eDisGo#316]
**Describe the bug**

For the test  `TestExamples.test_plot_example_ipynb`  `ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed` occurs. Automated tests fail for Python 3.7.

https://github.com/openego/eDisGo/actions/runs/3106803329/jobs/5034134907

https://github.com/openego/eDisGo/actions/runs/3106856573

**Screenshots**
```
 _____________________ TestExamples.test_plot_example_ipynb _____________________

self = <test_examples.TestExamples object at 0x7f563eb60390>

    @pytest.mark.slow
    def test_plot_example_ipynb(self):
        examples_dir_path = os.path.join(
            os.path.dirname(os.path.dirname(__file__)), "examples"
        )
        nb, errors = self._notebook_run(
>           os.path.join(examples_dir_path, "plot_example.ipynb")
        )

/home/runner/work/eDisGo/eDisGo/tests/test_examples.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/runner/work/eDisGo/eDisGo/tests/test_examples.py:44: in _notebook_run
    subprocess.check_call(args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['jupyter', 'nbconvert', '/home/runner/work/eDisGo/eDisGo/examples/plot_example.ipynb', '--output', '/tmp/tmpg8lm6mwp.ipynb', '--to', ...],)
kwargs = {}, retcode = 1
cmd = ['jupyter', 'nbconvert', '/home/runner/work/eDisGo/eDisGo/examples/plot_example.ipynb', '--output', '/tmp/tmpg8lm6mwp.ipynb', '--to', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['jupyter', 'nbconvert', '/home/runner/work/eDisGo/eDisGo/examples/plot_example.ipynb', '--output', '/tmp/tmpg8lm6mwp.ipynb', '--to', 'notebook', '--execute', '--ExecutePreprocessor.timeout=60']' returned non-zero exit status 1.

/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
[NbConvertApp] Converting notebook /home/runner/work/eDisGo/eDisGo/examples/plot_example.ipynb to notebook
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/traitlets/config/application.py", line 978, in launch_instance
    app.start()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 600, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 564, in convert_single_notebook
    notebook_filename, resources, input_buffer=input_buffer
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 492, in export_single_notebook
    notebook_filename, resources=resources
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 208, in from_file
    nbformat.read(file_stream, as_version=4), resources=resources, **kw
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 35, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 147, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 342, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 89, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 110, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/client.py", line 1025, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/client.py", line 919, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plot_plotly(
    edisgo_obj=edisgo_analyzed,
    grid=None,
    line_color="relative_loading",
    node_color="voltage_deviation",
    line_result_selection="max",
    node_result_selection="max",
    selected_timesteps=None,
    center_coordinates=True,
    pseudo_coordinates=False,
    node_selection=False
)

fig.show()
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_2318/1411934572.py in <module>
     12 )
     13 
---> 14 fig.show()

/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/plotly/basedatatypes.py in show(self, *args, **kwargs)
   3396         import plotly.io as pio
   3397 
-> 3398         return pio.show(self, *args, **kwargs)
   3399 
   3400     def to_json(self, *args, **kwargs):

/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/plotly/io/_renderers.py in show(fig, renderer, validate, **kwargs)
    395         if not nbformat or LooseVersion(nbformat.__version__) < LooseVersion("4.2.0"):
    396             raise ValueError(
--> 397                 "Mime type rendering requires nbformat>=4.2.0 but it is not installed"
    398             )
    399 

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed
```

**Comment by mltja** [comment]
No further support for 3.7
