### ISSUE TITLE
More generation capacity connected than imported

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#63]
In MVGD 2540 we get additional generation capacity for free :smirk: 

See the log, somehow additional generation capacity is added.

```
INFO:root:Grid expansion for ding0_grids__2540.pkl
DEBUG:edisgo:Cumulative generator capacity (existing): 13701.5 kW
DEBUG:edisgo:==> MV generators
DEBUG:edisgo:4 generators imported.
DEBUG:edisgo:Capacities of 0 of 3 existing generators updated (0 kW).
WARNING:edisgo:Generator 2021743 has no geom entry, EnergyMap's geom entry will be used.
DEBUG:edisgo:1 of 1 new generators added (566.0 kW).
DEBUG:edisgo:==> LV generators
DEBUG:edisgo:1199 generators imported.
DEBUG:edisgo:Capacities of 0 of 900 existing generators (single units) updated (0 kW).
DEBUG:edisgo:1199 of 1199 new generators added (1199 single units and 0 units as aggregated generators) (15199.9 kW).
DEBUG:edisgo:Cumulative generator capacity (updated): 17898.2 kW
Traceback (most recent call last):
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/guido/rli_local/eDisGo/edisgo/examples/example.py", line 55, in <module>
    network.import_generators()
  File "/home/guido/rli_local/eDisGo/edisgo/grid/network.py", line 212, in import_generators
    data_source=data_source)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 917, in import_generators
    _import_genos_from_oedb(network=network)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 1667, in _import_genos_from_oedb
    _validate_generation()
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 1602, in _validate_generation
    str(round(capacity_imported - capacity_grid, 1))
ValueError: Cumulative capacity of imported generators (17898.2 kW) differ from cumulative capacity of generators in updated grid (29467.4 kW) by -11569.2 kW.
```

**Comment by gplssm** [comment]
It turned out this a subsequent error due to fix at another point. #64 details the actual issue
