### ISSUE TITLE
More isolated nodes or edges

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#65]
```
INFO:root:Grid expansion for ding0_grids__2545.pkl
DEBUG:edisgo:Cumulative generator capacity (existing): 102.2 kW
DEBUG:edisgo:==> MV generators
DEBUG:edisgo:0 generators imported.
DEBUG:edisgo:Capacities of 0 of 0 existing generators updated (0 kW).
DEBUG:edisgo:0 of 0 new generators added (0 kW).
DEBUG:edisgo:==> LV generators
DEBUG:edisgo:16 generators imported.
DEBUG:edisgo:Capacities of 0 of 2 existing generators (single units) updated (0 kW).
DEBUG:edisgo:Capacities of 0 of 8 existing generators (in 0 of 3 aggregated units) updated (0 kW).
DEBUG:edisgo:6 of 6 new generators added (6 single units and 0 units as aggregated generators) (258.9 kW).
DEBUG:edisgo:Cumulative generator capacity (updated): 361.2 kW
DEBUG:edisgo:No valid conn. target found for Generator_1609798. Connected to LVStation_18129.
DEBUG:edisgo:No valid conn. target found for Generator_1612689. Connected to LVStation_18129.
ERROR:pypsa.io:Error, new components for Line are not unique
Traceback (most recent call last):
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/guido/rli_local/eDisGo/edisgo/examples/example.py", line 57, in <module>
    network.analyze()
  File "/home/guido/rli_local/eDisGo/edisgo/grid/network.py", line 260, in analyze
    self.pypsa = pypsa_io.to_pypsa(self, mode)
  File "/home/guido/rli_local/eDisGo/edisgo/tools/pypsa_io.py", line 186, in to_pypsa
    _check_integrity_of_pypsa(pypsa_network)
  File "/home/guido/rli_local/eDisGo/edisgo/tools/pypsa_io.py", line 896, in _check_integrity_of_pypsa
    raise ValueError("The graph has isolated nodes or edges")
ValueError: The graph has isolated nodes or edges
```

**Comment by gplssm** [comment]
The eDisGo graph is complete. Lines are entirety missing in PyPSA data

**Comment by nesnoj** [comment]
I found the problem and will fix it..

**Comment by nesnoj** [comment]
Problem: This MVGD contains 3 agg. LA. The lines which connect agg. genos or loads were not unique, I added the la_id to the line name..

I fixed it in fbb5928c6e420ed29410c97c03ce7c734acd67c4.

Furthermore, I will improve the "uniqueness"-check in `_check_topology()` now...
