### ISSUE TITLE
Line type for aggregated generators can't be determined

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#71]
For example in MVGD 458 eDisGo runs into trouble because the line type for lines connecting aggregated generators cannot be determined. There are aggregated generators because `agg_geno_new` is not empty, but [determination of the line type](https://github.com/openego/eDisGo/blob/999ac3177dd0813ab89ccd6f896074f2b233ce0d/edisgo/data/import_data.py#L1419-#L1421) fails due to empty `network.dingo_import_data`.

```
INFO:root:Grid expansion for ding0_grids__458.pkl
DEBUG:edisgo:Cumulative generator capacity (existing): 0 kW
DEBUG:edisgo:==> MV generators
DEBUG:edisgo:1 generators imported.
DEBUG:edisgo:Capacities of 0 of 0 existing generators updated (0 kW).
DEBUG:edisgo:1 of 1 new generators added (390.8 kW).
DEBUG:edisgo:==> LV generators
DEBUG:edisgo:1 generators imported.
DEBUG:edisgo:Capacities of 0 of 0 existing generators (single units) updated (0 kW).
DEBUG:edisgo:Capacities of 0 of 0 existing generators (in 0 of 0 aggregated units) updated (0 kW).
Traceback (most recent call last):
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/guido/rli_local/eDisGo/edisgo/examples/example.py", line 55, in <module>
    network.import_generators()
  File "/home/guido/rli_local/eDisGo/edisgo/grid/network.py", line 212, in import_generators
    data_source=data_source)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 923, in import_generators
    _import_genos_from_oedb(network=network)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 1670, in _import_genos_from_oedb
    generators_lv=generators_res_lv)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 1420, in _update_grids
    network.dingo_import_data.iloc[0]['agg_geno'],
  File "/home/guido/virtualenvs/eDisGo/lib/python3.5/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.5/site-packages/pandas/core/indexing.py", line 1749, in _getitem_axis
    self._is_valid_integer(key, axis)
  File "/home/guido/virtualenvs/eDisGo/lib/python3.5/site-packages/pandas/core/indexing.py", line 1638, in _is_valid_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by nesnoj** [comment]
Fixed in 2943cfaeb5725dff8cce8f95a7f8a6b75332bedd.
Instead of using an existing agg. line type for new agg. generators I use the max. available type from equipment.

**Comment by nesnoj** [comment]
Note for myself: Consider to use `select_cable()` instead to make sure it is able to carry the load.

**Comment by nesnoj** [comment]
Done in 63a4ec8aa8685d31beeb42ef50dfb967d952262e + f102f318a81ee176b63da80f0009764ecae9ed5b
