### ISSUE TITLE
import_from_ding0 detects aggregated generation falsely

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#73]
During import aggregated generation is detected and added in eDisGo as aggregated generator but Ding0 data has no aggregated LA.
```
INFO:keyring.backend:Loading Google
INFO:keyring.backend:Loading file
INFO:keyring.backend:Loading Windows (alt)
INFO:keyring.backend:Loading pyfs
INFO:keyring.backend:Loading keyczar
INFO:keyring.backend:Loading Gnome
INFO:keyring.backend:Loading multi
INFO:root:Grid expansion for ding0_grids__150.pkl
Traceback (most recent call last):
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-community-2017.1.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/guido/rli_local/eDisGo/edisgo/examples/example_modified.py", line 53, in <module>
    scenario=scenario)
  File "/home/guido/rli_local/eDisGo/edisgo/grid/network.py", line 200, in import_from_ding0
    network=network)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 91, in import_from_ding0
    _validate_ding0_grid_import(network.mv_grid, ding0_mv_grid, lv_grid_mapping)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 619, in _validate_ding0_grid_import
    _validate_load_generation(mv_grid, ding0_mv_grid)
  File "/home/guido/rli_local/eDisGo/edisgo/data/import_data.py", line 877, in _validate_load_generation
    if abs(v2['edisgo'] - v2['ding0']) > tol:
KeyError: 'ding0'
```

Find the reason why `import_from_ding0` identifies this generation capacity as aggregated

**Comment by gplssm** [comment]
The problem lies in the way the data validation gets eDisGo's aggregated generation at the substations bus bar. The condition is as follows
https://github.com/openego/eDisGo/blob/a3b3cc22b5d96ad066d90d897f73f3785bdc20b3/edisgo/data/import_data.py#L828-L831
which also includes generators accidentally located right next (or on top) of the substation. As it is the case here (line length ~0.45 cm).

May I implement the nodes group "generator-aggr" as a more stable solution. What do you think @nesnoj  ;-)

**Comment by nesnoj** [comment]
Hahaha, I love this one! :skull: :1st_place_medal: 
Yea, let's go for the "generator-aggr" solution :D

You gonna do it? As I need to detect agg. LA in a couple of locations it may be a good idea to hand it over to me?!

**Comment by nesnoj** [comment]
Done with some further modifications.
Since the oedb seems to be quite slow, I could not test it using more than one MVGD.
@gplssm Please test and close if everything is fine...

**Comment by nesnoj** [comment]
As you created a new full dataset, everything seems to be fine here?
