### ISSUE TITLE
AttributeError: 'Graph' object ... by runing eDisGo

### ISSUE THREAD

**Issue by wolfbunke** [openego/eDisGo#89]
Hi @gplssm @maltesc,

I tried to install and use eDisGo in the [specs branch](https://github.com/openego/eGo/blob/features/specs/ego/test_ego.py) of eGo. After fixing few package / version problems I run into following error:
```
Traceback (most recent call last):
  File "test_ego.py", line 209, in <module>
    scenario=scenario)
  File "/home/dozeumbuw/ego_env/src/eDisGo/edisgo/grid/network.py", line 142, in import_from_ding0
    network=network)
  File "/home/dozeumbuw/ego_env/src/eDisGo/edisgo/data/import_data.py", line 86, in import_from_ding0
    ding0_mv_grid.close_circuit_breakers()
  File "/home/dozeumbuw/ego_env/lib/python3.5/site-packages/ding0/core/network/grids.py", line 100, in close_circuit_breakers
    circ_breaker.close()
  File "/home/dozeumbuw/ego_env/lib/python3.5/site-packages/ding0/core/network/__init__.py", line 581, in close
    self.grid._graph.add_edge(self.branch_nodes[0], self.branch_nodes[1], branch=self.branch)
  File "/home/dozeumbuw/ego_env/lib/python3.5/site-packages/networkx/classes/graph.py", line 872, in add_edge
    if u not in self._node:
AttributeError: 'Graph' object has no attribute '_node'
```
Is it a DB data problem, do I use the wrong branches or something else? I am working on the eGo Branch `origin/features/specs` with 
ding0 on ` origin/dev` , eDisGo on `origin/features/etrago_timeseries` and ego.io on `origin/feature/improve-db-connec`. Do you have any idea?

**Comment by maltesc** [comment]
This problem sounds familiar and I think it is a dependency issue. Please check https://github.com/openego/eDisGo/issues/78, I am quite sure this solved the problem for me.

**Comment by wolfbunke** [comment]
ok, thank you!  I will close this issue and use #78

**Comment by gplssm** [comment]
If I remember correctly, this problem is due to NetworkX 2.0. Please use 1.11

**Comment by wolfbunke** [comment]
ok, thank you
